"use client";
import { useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowRight, ArrowUpRight, ChevronDown, Terminal } from "lucide-react";
import { useExperience } from "./experience";
const cases = [
 { id:'SOA—001', category:'OPERATIONS / AUTOMATION', title:'Connect intake,\ntask routing and reporting.', problem:'Disconnected tools. Repeated data entry. No single source of truth.', solution:'A request is submitted once and reaches the right team. Exceptions stay visible for human review.', outcome:'One coordinated workflow, with a human in control.', detail:'A request enters once, is checked against business rules, and reaches the right team. Exceptions pause for review; every handoff remains traceable.', before:['EMAIL','SHEETS','HANDOFF'], after:['INTAKE','ORCHESTRATE','REVIEW'], focus:'Connected operations' },
 { id:'SOA—002', category:'INTELLIGENCE / CUSTOM SOFTWARE', title:'Bring operational information\ninto one view.', problem:'Critical decisions buried across spreadsheets and legacy systems.', solution:'Connect the data held in spreadsheets and existing systems into one view.', outcome:'A shared view of what matters and what needs attention.', detail:'Role-specific views surface bottlenecks and ownership. Data stays connected to its source, so teams can move from a signal to the underlying record.', before:['SILOS','EXPORTS','GUESSWORK'], after:['SOURCES','COMMAND','DECISION'], focus:'Operational command center' },
];
export function Blueprints(){
 const {enabled,setFocus}=useExperience();
 const [open,setOpen]=useState<number|null>(null);
 const [view,setView]=useState<'before'|'after'>('after');
 return <section id="blueprints" className="section shell" aria-labelledby="blueprints-title"><div className="section-eyebrow mono"><span className="tiny-cross">+</span> DECLASSIFIED BLUEPRINTS<span className="eyebrow-line"/><span className="section-index">04 / POSSIBILITIES</span></div><div className="section-heading"><h2 id="blueprints-title">Examples of<br/><span className="muted-heading">what we can build.</span></h2><p className="body-copy">These examples show possible approaches to common operational problems. They are illustrative concepts, not completed client projects.</p></div><div className="blueprints-grid grid md:grid-cols-2 gap-5">{cases.map((item,i)=><article className={`terminal-card ${open===i?'terminal-open':''}`} key={item.id}><div className="terminal-bar"><div className="terminal-dots"><i/><i/><i/></div><span className="mono">{item.id} / CONCEPT BLUEPRINT</span><Terminal size={14}/></div><div className="terminal-body"><div className="terminal-title"><span className="mono terminal-category">{item.category}</span><h3>{item.title.split('\n').map((line,j)=><span key={j}>{line}<br/></span>)}</h3></div><dl>{[['FRICTION',item.problem],['INTERVENTION',item.solution],['INTENDED OUTCOME',item.outcome]].map(([label,value])=><div key={label}><dt className="mono"><span>›</span>{label}</dt><dd>{value}</dd></div>)}</dl><button className="blueprint-inspect mono" onClick={()=>{setOpen(open===i?null:i);setView('after');}} aria-expanded={open===i} aria-controls={`blueprint-${i}`}>{open===i?'CLOSE BLUEPRINT':'INSPECT ARCHITECTURE'}<ChevronDown size={16}/></button><AnimatePresence initial={false}>{open===i&&<motion.div id={`blueprint-${i}`} className="blueprint-expanded" initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}} transition={{duration:enabled?.3:0}}><div className="flow-toggle" role="group" aria-label="Compare architecture"><button aria-pressed={view==='before'} onClick={()=>setView('before')}>The bottleneck</button><button aria-pressed={view==='after'} onClick={()=>setView('after')}>The architecture</button></div><div className={`blueprint-flow ${view}`} aria-label={view==='before'?'Disconnected system':'Connected system'}>{item[view].map((node,n)=><motion.div layout key={n} className="flow-piece"><motion.span animate={{borderColor:view==='after'?'#a37738':'#49433d',y:enabled&&view==='before'?(n%2?6:-6):0}} transition={{duration:.35}}>{node}</motion.span>{n<2&&<motion.i animate={{opacity:view==='after'?1:.15}}><ArrowRight size={14}/></motion.i>}</motion.div>)}</div><p>{view==='before'?item.problem:item.detail}</p><a href="#intake" onClick={()=>setFocus(item.focus)} className="blueprint-cta">Use this as a starting point<ArrowUpRight size={16}/></a></motion.div>}</AnimatePresence></div></article>)}</div></section>;
}
