import type { Metadata } from "next";
import Link from "next/link";
import { PageShell } from "../components/page-shell";
import { ContactDetails } from "../components/site-footer";

export const metadata: Metadata = { title: "Enquiry privacy | State of Ashes", description: "How State of Ashes uses the information you provide when making a business technology enquiry.", alternates: { canonical: "/privacy" }, openGraph: { title: "Enquiry privacy | State of Ashes", description: "Information about your enquiry and how to contact us about it.", url: "/privacy" } };

export default function PrivacyPage() {
  return <PageShell><article className="shell privacy-copy"><Link href="/" className="text-link">← Home</Link><p className="section-eyebrow mono">ENQUIRY PRIVACY / UPDATED 7 OCTOBER 2026</p><h1>Your enquiry information.</h1><p className="information-lead">We use the details you provide to understand your request and follow up with you.</p><h2>What the forms collect</h2><p>The main form asks for your name, email address and a description of what you need. The guided enquiry also asks for a topic and urgency, with optional company, location and current-system details.</p><h2>How the information is used</h2><p>Your enquiry is used to assess the work, communicate with you and keep a record of that conversation. Submitting an enquiry does not sign you up for marketing.</p><h2>Where it goes</h2><p>The website is hosted on Vercel. The enquiry system is designed to store records in Supabase and send notifications and acknowledgment emails through Resend. These providers may process information outside South Africa. Delivery and storage depend on the services being available and configured.</p><h2>Keep sensitive information out</h2><p>Please do not submit passwords, one-time codes, confidential records or personal information about other people. If further information is needed, we will discuss how to share it.</p><h2>Questions or changes</h2><p>Contact Lucian to ask about your enquiry, correct its details or request deletion. We will discuss your request and any record that needs to be retained for work already agreed.</p><ContactDetails/><p className="privacy-return"><Link href="/#intake">Return to the enquiry form →</Link></p></article></PageShell>;
}
